# Generated by Django 5.0.6 on 2024-07-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyApp", "0003_problem_difficulty_problem_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="difficulty",
            field=models.CharField(
                choices=[("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                default="Medium",
                max_length=6,
            ),
        ),
    ]
