# Generated by Django 5.0.6 on 2024-07-15 07:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MyApp", "0004_alter_problem_difficulty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem",
            old_name="desc",
            new_name="description",
        ),
    ]
