# Generated by Django 5.0.6 on 2024-07-23 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MyApp", "0008_remove_problem_hidden_tc_problem_expected_output_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem",
            old_name="custom_tc",
            new_name="sample_op",
        ),
    ]
